import React from "react";

export default function MetabolicType(){
  return (
    <div>

  <h1>What are the three doshas?</h1>
<h2 className="dosha-title">Kapha dosha</h2>
<p>Kapha types have strong frames and are naturally athletic as long they are exercising regularly to manage their tendency to gain weight. The influence of the earth and water elements makes them innately stable, compassionate, and loyal. They appreciate doing things in a methodical, step-by-step manner, and prefer a regular routine in their personal and professional lives. When imbalanced they can become unmotivated, stubborn, and complacent even when change is necessary. Their metabolism tends to be slow and their appetite for both food and stimulation is less intense than vata or pitta types. They benefit from exposing themselves to new environments, people, and occasionally fasting.</p>

<h2 className="dosha-title">Pitta dosha</h2>
<p> Pitta types are dominated by the fire element, which makes them innately strong, intense, and irritable. They tend to have a medium build and endurance with powerful musculature. They often have freckled skin that easily reddens in the sun, during exercise, massage, and when blushing. They are strong willed and good at doing what they think is right. They approach work and play with the same intensity and competitiveness. They are natural leaders and quick learners whose ability to easily comprehend and master new skills and concepts can make them judgmental or impatient toward people they feel are slower or less focused than themselves. They have strong digestion and intense appetites, both for food and challenges. If they miss a meal they are likely to become grumpy and may take a “bite” out of somebody instead. It is common for them to suffer from health conditions such as inflammation, rashes, acne, and loose stool. For balance, pittas need to manage their “fiery” tendencies, channeling them in productive ways and learning to recognize their destructive power.</p>

<h2 className="dosha-title">Vata dosha</h2>
<p>Vata types tend to be thin and lanky. They are very mentally and physically active and enjoy creative endeavors, meeting new people, and traveling to new places. When they are balanced, vatas are flexible, have lively imaginations, and are original thinkers. When imbalanced they can get anxious, ungrounded, and can seem “flaky” about fulfilling commitments, sticking to a routine, and completing projects. They tend to run cold and dry and enjoy warm, humid weather. It’s common for vata types to experience cold hands and feet, constipation, dry skin, and cracking joints. The influence of the air element in their constitution causes their energy, mood, and appetite to fluctuate dramatically. For this reason vata types often fail to eat and sleep regularly, swinging from eating heavy foods to ground and sedate themselves, or ingesting stimulants like coffee and sugar to sustain intense physical or mental activity. Insomnia and low immunity are very common problem for the sensitive vata person. </p>

<h2 className="dosha-title">What does it mean to be bi-doshic?</h2>
<p>Bi-doshic indicates that you share qualities strongly with two doshic types, and is actually how most of us are. People with dual constitutions (vata-pitta, pitta-kapha, and vata-kapha) are, in a sense, “split.” Under certain conditions, one dosha will predominate and under other circumstances the other dosha will. The best way to manage bi-doshic prakriti is by the season. For example, if you have a vata-pitta or vata-kapha prakriti, during autumn, which is a vata season, you’d follow a vata-decreasing regimen. During warm weather, you’d follow a pitta-decreasing regimen. During the cold and wet season, you’d follow kapha.</p>

<h2 className="dosha-title">Can a person be tri-doshic?</h2>
<p>Tri-doshic means having equal amounts of each doshic influence. The tri-doshic person can be very strong, stable, and adaptable when in balance. When they are out of balance, however, they can experience poor health. The key is to preserving your personal balance is to hone your sensitivity for noticing potential imbalances that may arise from your environment or from dietary or emotional imbalances, and to adopt practices that will counter-balance these influences. For example, in autumn, a tri-doshic person would act if they were a person with a vata constitution and follow a vata-balancing lifestyle and diet. The same is true for the other seasons: Employ a pitta-balancing regimen when the weather is hot and a kapha-balancing regimen when the weather is cold and damp.</p>
</div>);
}
